### ISSUE TITLE
dishes belongs to categories

### ISSUE THREAD

**Issue by Sajaas** [CraftAcademy/slow_food_sinatra_august_17#20]
As a restaurant owner
In order to make the menu easy to navigate
I would like to assign dishes to different categories

**Comment by olofvi** [comment]
write a a scenario for categories

**Comment by Sajaas** [comment]
- [x] Create feature branch
- [x] Update feature file
- [x] Scenario: specific dish belongs to a category
- [x] Scenario: customer goes in to the site, and can see the menu where the dishes belongs to categories
- [x] Add some HTML love to the template
