### ISSUE TITLE
Add dishes to order

### ISSUE THREAD

**Issue by andreademoja** [CraftAcademy/slow_food_sinatra_august_17#8]
As a customer
In order to get a Carbonara
I would like to press "add to order" to be able to add Carbonara to my order

**Comment by Sajaas** [comment]
- [x] Create feature branch
- [x] Create feature file
- [ ] Scenario: customer adds dish to order
- [ ] Scenario: customer adds several dishes of the same kind to order
- [ ] Add some HTML love to the template
