### ISSUE TITLE
Display dish price & description

### ISSUE THREAD

**Issue by andreademoja** [CraftAcademy/slow_food_sinatra_august_17#9]
As a customer
In order to make a decision what dish to buy
I would like to see the price and description of each dish in the menu

**Comment by tochman** [comment]
- [x] Create a feature branch - called show_dish_info
- [x] Create/modify existing a feature file
- [x] Add properties to Dish (price and description?)
- [x] Show info on view (the menu) 
- [x] Add some HTML love to the template

**Comment by Sajaas** [comment]
Preview of our site so far:
![Screen Shot 2017-09-07 at 14.58.17.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59afb05b855bb60011626140/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772a6454f46b7191a379eb0c2e59415e49be5d4a1f06a3a3dc78e2a436628f555abb836d5627c56c14a8e9d41fbf07e823dd1c81b5bf9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ec85cf143e84c50a01a3664f43b.png)
